# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import os
import pathlib
import typing
__all__ = [
    "Sketch",
    "Solid",
    "bezier",
    "box",
    "bspline",
    "circle",
    "cone",
    "cylinder",
    "get_memory_limit",
    "intersect",
    "polygon",
    "rectangle",
    "set_memory_limit",
    "sphere",
    "square",
    "subtract",
    "union",
]

@typing.final
class Sketch:
    r"""
    A lazily-evaluated 2D shape in the XY plane, built out of `csgpy`
    primitives (`circle(..)`, `square(..)`, `rectangle(..)`, `polygon(..)`)
    and boolean/transform operations - the 2D counterpart to [`Solid`].
    
    Turn it into a [`Solid`] with `.extrude(..)`, `.extrude_vector(..)`,
    `.revolve(..)` or `.sweep(..)`.
    """
    def translate(self, dx: builtins.float, dy: builtins.float) -> Sketch:
        r"""
        Move this sketch by `(dx, dy)`. Returns a new, still-lazy `Sketch`.
        """
    def rotate(self, deg: builtins.float) -> Sketch:
        r"""
        Rotate this sketch by `deg` degrees about the origin (a sketch is
        planar, so - unlike `Solid.rotate` - there's only one axis to turn
        around).
        """
    def scale(self, sx: builtins.float, sy: typing.Optional[builtins.float] = None) -> Sketch:
        r"""
        Scale this sketch by `(sx, sy)`, or uniformly if only `sx` is given.
        """
    def union(self, other: Sketch) -> Sketch:
        r"""
        Boolean union with `other`. Same as `self + other`.
        """
    def subtract(self, other: Sketch) -> Sketch:
        r"""
        Boolean subtraction of `other` from `self`. Same as `self - other`.
        """
    def intersect(self, other: Sketch) -> Sketch:
        r"""
        Boolean intersection with `other`. Same as `self & other`.
        """
    def __add__(self, other: Sketch) -> Sketch: ...
    def __or__(self, other: Sketch) -> Sketch: ...
    def __sub__(self, other: Sketch) -> Sketch: ...
    def __and__(self, other: Sketch) -> Sketch: ...
    def extrude(self, height: builtins.float) -> Solid:
        r"""
        Linearly extrude this sketch `height` units up the Z axis into a
        [`Solid`]. Shorthand for `extrude_vector(0, 0, height)`.
        """
    def extrude_vector(self, dx: builtins.float, dy: builtins.float, dz: builtins.float) -> Solid:
        r"""
        Linearly extrude this sketch along an arbitrary `(dx, dy, dz)`
        direction vector into a [`Solid`] - e.g. a non-zero `dx`/`dy` gives a
        slanted (sheared) extrusion instead of a straight-up one.
        """
    def revolve(self, angle_degs: builtins.float = 360.0, segments: builtins.int = 32) -> Solid:
        r"""
        Revolve this sketch around the Y axis into a surface of revolution
        (a lathed [`Solid`]) - e.g. a rectangle offset from the axis makes a
        ring/tube, a right-triangle profile makes a cone.
        
        `angle_degs` is the sweep angle (360 for a full solid of revolution,
        less for a wedge with flat end caps); `segments` is the number of
        angular subdivisions and must be at least 2.
        """
    def sweep(self, path: typing.Sequence[tuple[builtins.float, builtins.float, builtins.float]]) -> Solid:
        r"""
        Sweep (extrude-along-a-path): duplicate this sketch at every point of
        `path` (a list of `(x, y, z)` points), aiming its +Z at the local
        path tangent, and stitch the copies into a [`Solid`] - e.g. a circle
        swept along points on an arc, or along a helix for a screw-like
        shape. If `path`'s first and last points coincide it's treated as a
        closed loop and no end caps are added.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Solid:
    r"""
    A lazy 3D solid built out of `csgrs` primitives and boolean/transform
    operations.
    
    Nothing is meshed until it's needed: `.to_mesh()`, `.save_stl()`,
    `.save_obj()` (and rendering, which calls `.to_mesh()`) is what triggers
    evaluation, and the result is cached on this instance so repeat calls
    don't redo the work.
    """
    def translate(self, dx: builtins.float, dy: builtins.float, dz: builtins.float) -> Solid:
        r"""
        Move this solid by `(dx, dy, dz)`. Returns a new, still-lazy `Solid`.
        """
    def rotate(self, rx: builtins.float = 0.0, ry: builtins.float = 0.0, rz: builtins.float = 0.0) -> Solid:
        r"""
        Rotate this solid by the given angles in degrees, about X, Y, Z in turn.
        """
    def scale(self, sx: builtins.float, sy: typing.Optional[builtins.float] = None, sz: typing.Optional[builtins.float] = None) -> Solid:
        r"""
        Scale this solid by `(sx, sy, sz)`, or uniformly if only `sx` is given.
        """
    def union(self, other: Solid) -> Solid:
        r"""
        Boolean union with `other`. Same as `self + other`.
        """
    def subtract(self, other: Solid) -> Solid:
        r"""
        Boolean subtraction of `other` from `self`. Same as `self - other`.
        """
    def intersect(self, other: Solid) -> Solid:
        r"""
        Boolean intersection with `other`. Same as `self & other`.
        """
    def __add__(self, other: Solid) -> Solid: ...
    def __or__(self, other: Solid) -> Solid: ...
    def __sub__(self, other: Solid) -> Solid: ...
    def __and__(self, other: Solid) -> Solid: ...
    def to_mesh(self) -> tuple[builtins.list[tuple[builtins.float, builtins.float, builtins.float]], builtins.list[tuple[builtins.int, builtins.int, builtins.int]]]:
        r"""
        Force evaluation of the lazy tree (cached after the first call) and
        return `(vertices, triangles)`: a list of `(x, y, z)` points and a
        list of `(i, j, k)` index triples into that list.
        """
    def save_stl(self, path: builtins.str | os.PathLike | pathlib.Path, ascii: builtins.bool = False) -> None:
        r"""
        Write this solid to an STL file - the standard format for 3D printing
        (slicers) and CAD. Binary by default (compact, fast to load); pass
        `ascii=True` for a human-readable text file instead.
        """
    def save_obj(self, path: builtins.str | os.PathLike | pathlib.Path) -> None:
        r"""
        Write this solid to a Wavefront OBJ file - the most widely supported
        general 3D format (Blender, game engines, web viewers, CAD tools).
        
        Corners at the same position are written once and shared between
        triangles (unlike STL, which repeats them per triangle); each
        triangle gets a flat per-face normal.
        """
    def __repr__(self) -> builtins.str: ...

def bezier(control: typing.Sequence[tuple[builtins.float, builtins.float]], segments: builtins.int = 32) -> Sketch:
    r"""
    A Bezier curve in the XY plane, sampled from its `control` points. If the
    sampled curve comes back around to its start (e.g. the last control
    point equals the first) it's a closed, fillable profile - otherwise it's
    an open poly-line (useful as a `sweep()` path, not as an `extrude()`
    base).
    """

def box(width: builtins.float, length: builtins.float, height: builtins.float) -> Solid:
    r"""
    An axis-aligned box (cuboid) of the given width (X), length (Y) and
    height (Z), centered on the origin's corner at `(0, 0, 0)`.
    """

def bspline(control: typing.Sequence[tuple[builtins.float, builtins.float]], degree: builtins.int = 3, segments_per_span: builtins.int = 8) -> Sketch:
    r"""
    An open-uniform B-spline of the given `degree` (3 = cubic) through
    `control` points, in the XY plane - a *soft*, tangent-continuous curve
    (unlike `polygon()`, which is a sharp-cornered polyline through the same
    points). Closed the same way as `bezier()`.
    """

def circle(radius: builtins.float, segments: builtins.int = 32) -> Sketch:
    r"""
    A 2D circle of the given radius in the XY plane, centered on the
    origin.
    """

def cone(radius: builtins.float, height: builtins.float, segments: builtins.int = 32) -> Solid:
    r"""
    A cone of the given base radius and height, standing on the XY plane
    with its base centered at `(0, 0, 0)`.
    """

def cylinder(radius: builtins.float, height: builtins.float, segments: builtins.int = 32) -> Solid:
    r"""
    A cylinder of the given radius and height, standing on the XY plane
    with its base centered at `(0, 0, 0)`.
    """

def get_memory_limit() -> typing.Optional[builtins.int]:
    r"""
    The current cap from `set_memory_limit`, in megabytes (`None` if uncapped).
    """

def intersect(a: Solid, b: Solid) -> Solid:
    r"""
    Boolean intersection of `a` and `b`. Same as `a & b`.
    """

def polygon(points: typing.Sequence[tuple[builtins.float, builtins.float]]) -> Sketch:
    r"""
    A 2D polygon in the XY plane from an ordered list of `(x, y)` points
    (closed automatically if the first and last points don't already
    match).
    """

def rectangle(width: builtins.float, length: builtins.float) -> Sketch:
    r"""
    A 2D rectangle of the given width (X) and length (Y), with one corner
    at `(0, 0)`.
    """

def set_memory_limit(megabytes: typing.Optional[builtins.int]) -> None:
    r"""
    Cap how much memory this Python process may use while csgpy evaluates a
    solid, in megabytes (`None` for no cap). A computation that runs past it
    ends the process instead of making the whole machine unresponsive.
    
    Defaults to half the machine's RAM, or the `CSGPY_MEMORY_LIMIT_MB`
    environment variable if set (`0` meaning no cap). Enforced on Windows and
    Linux; a no-op on macOS.
    """

def sphere(radius: builtins.float, segments: builtins.int = 32, stacks: builtins.int = 16) -> Solid:
    r"""
    A sphere of the given radius, centered at `(0, 0, 0)`.
    """

def square(width: builtins.float) -> Sketch:
    r"""
    A 2D square of the given width, in the XY plane, with one corner at
    `(0, 0)`.
    """

def subtract(a: Solid, b: Solid) -> Solid:
    r"""
    Boolean subtraction of `b` from `a`. Same as `a - b`.
    """

def union(a: Solid, b: Solid) -> Solid:
    r"""
    Boolean union of `a` and `b`. Same as `a + b`.
    """

